package server

// Development-only self-signed certificate
// DO NOT use in production - generate real certificates with gorelay init

var devCertPEM = []byte(`-----BEGIN CERTIFICATE-----
MIIBhTCCASugAwIBAgIQIRi6zePL6mKjOipn+dNuaTAKBggqhkjOPQQDAjASMRAw
DgYDVQQKEwdBY21lIENvMB4XDTE3MTAyMDE5NDMwNloXDTE4MTAyMDE5NDMwNlow
EjEQMA4GA1UEChMHQWNtZSBDbzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABLU3
jSQKKmo/6yULMuEsNBKvIBftBOT4lYLZPgiIYTHlRMS3DO04LD2kFLsBGas5wEm2
AYIEZFkPJRYThGRcJNGjYzBhMA4GA1UdDwEB/wQEAwICpDATBgNVHSUEDDAKBggr
BgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdEQQiMCCCDmxvY2FsaG9zdDo1
NDUzgg4xMjcuMC4wLjE6NTQ1MzAKBggqhkjOPQQDAgNIADBFAiEA2wpSek3WX64h
kkRJBECDHPPqA64BLBE3kIhj9LGwH2cCIBJlYGIT6fzMPLqDXfQB+3sDxpd9aN4G
aN5IN3JUXfS1
-----END CERTIFICATE-----`)

var devKeyPEM = []byte(`-----BEGIN EC PRIVATE KEY-----
MHQCAQEEIIrYSSNQFaA2Hwf583QmKbyavkgoftpCYhP8lk6RWRHmoAcGBSuBBAAi
oWQDYgAEF5Qscy3GRIczDHaRUhlOPCRAPCj2RCZTnMRGzE1+hHAMQ0v/dBMJ86VP
3aWsLdS3FgCb8GeH78K34OAWZIXQ1iHbl9hm/bzHB+bU7obHVJEmDJ+zz0IZFAPR
zAxEH8OX
-----END EC PRIVATE KEY-----`)
