/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Research',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'research' },
      ],
    },
    {
      type: 'category',
      label: 'GRP Protocol',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'protocol' },
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'architecture' },
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'deployment' },
      ],
    },
    {
      type: 'category',
      label: 'Development',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'development' },
      ],
    },
    {
      type: 'category',
      label: 'Session Log',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'session-log' },
      ],
    },
  ],
};

module.exports = sidebars;
